### ISSUE TITLE
Can't install newer versions of node

### ISSUE THREAD

**Issue by svallory** [poise/poise-javascript#1]
Trying to run this resource:

``` ruby
javascript_runtime 'myapp' do
    provider :system
    options :system, package_name: 'nodejs', package_version: '4.3.1'
  end
```

Gives me this error:

`Package nodejs would install 4.3.1-1nodesource1~trusty1, which does not match myapp. Please set the package_name or package_version provider options.`

But if I change it to 

``` ruby
javascript_runtime '4.3.1' do
    provider :system
    options :system, package_name: 'nodejs', package_version: '4.3.1'
  end
```

or add `version '4.3.1'` I get:

`Package nodejs-dev would install 0.10.25~dfsg2-2ubuntu1, which does not match 4.3.1. Please set the package_name or package_version provider options.`

**Comment by coderanger** [comment]
The first is definitely a bug and needs to be fixed, but would yield the second anyway. The second is because the nodesource repo has the development packages as `nodejs-dbg` instead of `nodejs-dev` so you're getting a mismatch (which is why that check exists :-) ). You should be able to fix it by making that:

``` ruby
options :system, package_name: 'nodejs', package_version: '4.3.1', dev_package: 'nodejs-dbg'
```

**Comment by coderanger** [comment]
Or you could set `dev_package` to false to skip it if you don't think you need it.

**Comment by coderanger** [comment]
Closing this out as I don't think I can fix it other than to say nodesource should use standard package names.
